import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/shared/ThemeProvider";
import AiTutor from "@/components/shared/AiTutor";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import AiMSPreloader from "@/components/shared/AiMSPreloader";

// 👉 STEP 1: Import your new AI component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // suppressHydrationWarning is REQUIRED by next-themes so it doesn't throw errors
    <html lang="en" suppressHydrationWarning>
      <body>

        <ThemeProvider
          attribute="class"
          defaultTheme="system" // Automatically matches their PC/Phone settings
          enableSystem
          disableTransitionOnChange
        >
          <Navbar transparent={true} />
          {/* This renders whatever page the user is currently on */}
          {children}
          <Footer />
          {/* 👉 STEP 2: The Omnipresent Widget! */}
          {/* Because it's outside of {children}, it will float on top of every route. */}
          <AiTutor />
        </ThemeProvider>
      </body>
    </html>
  );
}
